apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meu-site
  template:
    metadata:
      labels:
        app: meu-site
    spec:
      containers:
      - name: nginx
        image: ageuleandro/app-html:15c347dbe05d11a894d53c30c846ea12f12f353a
        ports:
        - containerPort: 80
