name: Build, Push Docker Image and Deploy to EKS

on:
  push:
    branches:
      - main  # Altere se usar outra branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: sa-east-1
          role-to-assume: arn:aws:iam::YOUR_ACCOUNT_ID:role/YOUR_ROLE_NAME
          role-session-name: github-actions-session
          
          # Se você não usar role, substitua por:
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ageuleandro/app-html:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ageuleandro/app-html:${{ github.sha }}

      - name: Update Kubernetes deployment image
        run: |
          kubectl set image deployment/meu-site nginx=ageuleandro/app-html:${{ github.sha }}
          kubectl rollout status deployment/meu-site
