name: PrimeiroProjeto

on:
  push:
    branches: [main]

jobs:
  PrimeiroProjeto: 
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v4.2.2

      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{  secrets.USER  }}
          password: ${{  secrets.PASSWD  }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: |
            ageuleandro/primeiro-projeto:v1
            ageuleandro/primeiro-projeto:latest
      
